FROM ubuntu:22.04

ARG DOCKER_USER=dev

COPY docker/bashrc /etc/bash.bashrc
RUN chmod a+rwx /etc/bash.bashrc

RUN apt-get update && apt-get install --yes --no-install-recommends \
  lsb-release wget software-properties-common gnupg \
  build-essential make ninja-build ccache cmake python3 python3-pip lcov sudo

RUN python3 -m pip install conan==1.60.2

RUN useradd --create-home --shell /bin/bash --groups sudo $DOCKER_USER

USER $DOCKER_USER